import '../styles/globals.css'

export const metadata = {
  title: 'El Correo de Yury',
  description: 'Generated by Next.js',
  icons: {
    icon: 'icon.ico'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
